on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - snapshot
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: cask/setup-cask@master
        with:
          version: snapshot
      - run: make compile

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - snapshot
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: cask/setup-cask@master
        with:
          version: snapshot
      # - name: Debugging with ssh
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     limit-access-to-actor: true
      #     limit-access-to-users: wyuenho
      # - name: Install packages
      #   run: |
      #     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
      #     sudo add-apt-repository ppa:rmescandon/yq
      #     sudo apt update
      #     sudo apt-get -y install ca-certificates sqlite3 yq
      #     go install github.com/pelletier/go-toml/v2/cmd/tomljson@latest
      #     export PATH="$(go env GOPATH)/bin:$PATH"
      - name: Run tests
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt-get -y install ca-certificates sqlite3 yq
          go install github.com/pelletier/go-toml/v2/cmd/tomljson@latest
          export PATH="$(go env GOPATH)/bin:$PATH"
          make test
