on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - snapshot
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: cask/setup-cask@master
        with:
          version: snapshot
      - run: make compile

  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       emacs-version:
  #         - 26.1
  #         - 26.2
  #         - 26.3
  #         - 27.1
  #         - 27.2
  #         - 28.1
  #         - snapshot
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: purcell/setup-emacs@master
  #       with:
  #         version: ${{ matrix.emacs-version }}
  #     - uses: cask/setup-cask@master
  #       with:
  #         version: snapshot
  #     - run: make test
