on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - "26.1"
          - "26.2"
          - "26.3"
          - "27.1"
          - "27.2"
          - "28.1"
          - "29.1"
          - "snapshot"
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: cask/setup-cask@master
        with:
          version: 0.9.0
      - run: make compile

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - "26.1"
          - "26.2"
          - "26.3"
          - "27.1"
          - "27.2"
          - "28.1"
          - "29.1"
          - "snapshot"
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: cask/setup-cask@master
        with:
          version: snapshot
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
      - name: Install packages
        run: |
          go install github.com/pelletier/go-toml/v2/cmd/tomljson@latest
      - name: Run tests
        run: |
          make test
